version: "3.0"
services:
  db:
    image: mysql:8.0.28
    container_name: post_manage
    environment:
      MYSQL_DATABASE: postManage
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - postmanage

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/postmanage?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postmanage
    container_name: post_manage_app

networks:
  postmanage: